on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows
          - macos
          - ubuntu
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - run: |
          npm install-ci-test
          npx package
          mv ../courselore.${{ matrix.os == 'windows' && 'zip' || 'tar.gz' }} ./courselore--${{ matrix.os }}--${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || github.sha }}.${{ matrix.os == 'windows' && 'zip' || 'tar.gz' }}
      - uses: actions/upload-artifact@main
        with:
          path: ./courselore--${{ matrix.os }}--${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || github.sha }}.${{ matrix.os == 'windows' && 'zip' || 'tar.gz' }}
          name: courselore--${{ matrix.os }}--${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || github.sha }}.${{ matrix.os == 'windows' && 'zip' || 'tar.gz' }}
      - if: ${{ matrix.os == 'ubuntu' && startsWith(github.ref, 'refs/tags/v') }}
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - if: ${{ matrix.os == 'ubuntu' && startsWith(github.ref, 'refs/tags/v') }}
        run: |
          cat >> ~/.ssh/known_hosts << "EOF"
            # $ ssh-keyscan courselore.org
            # courselore.org:22 SSH-2.0-OpenSSH_10.2p1 Ubuntu-2ubuntu3.6
            # courselore.org:22 SSH-2.0-OpenSSH_10.2p1 Ubuntu-2ubuntu3.6
            courselore.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDL/ZFWuUq7tipz/+vx/jbXYeJpvt7dDgMhrz1erOrtf8kT6aK7A9Q3r/VxGmfYTam96RVaAsRcivuvOafwSw4OGGkUXYBBWYwWDNkwuX+dfQx71SVFHeQlEC5e0jlk50Kjh1HsjRubz+ng/7/FentSNqbZdB7vBVu7lQLGBodUiczfZ3HXn1DLaDb6D8gkMS6prLaFJ7Nof+3Pkmi3QrtOIHVzFbypx87GuCDErzW3/QJ3hplKXbC9NVa83IYKdPbZCF/3WuvCCVi5KG8OV2TKVQhdCphhfdqAjiu8AFqJ7wMojUkUM+1oFv4Ix5N64YJvgFTzU0ifQ4ZiruYTxh52yBa32RP0mHSQKQvF8O676zrT6MufkgTMeMhoQbmYB2pLJHh9rWS7Bo84I/BXPhLgP7e1L8vNXhtmOkbYOqjoeXE8Qr2w5wrYzI77eAzBAni0zaPL7wB1t/NrhL8kRIlV2sZ/K4P11PCPZY+8qxXJbnIp9OOBqhQ7BDxBbQOTmtM=
            # courselore.org:22 SSH-2.0-OpenSSH_10.2p1 Ubuntu-2ubuntu3.6
            courselore.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJIL3HXFm12745u+CWWOeTu07jvu13yttKxDauiqXRB/EJTu3jnn5dw5e0m3BCIt//owbwlOZ7ojOdokgC7WIKQ=
            # courselore.org:22 SSH-2.0-OpenSSH_10.2p1 Ubuntu-2ubuntu3.6
            courselore.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPjvJXcgMS0iNdO7NLuf4pfEj5fX0f6jhe9Na6Wp2IQL
            # courselore.org:22 SSH-2.0-OpenSSH_10.2p1 Ubuntu-2ubuntu3.6
          EOF
          rsync -a ./courselore--ubuntu--${{ github.ref_name }}.tar.gz root@courselore.org:/root/courselore--ubuntu--${{ github.ref_name }}.tar.gz
          ssh root@courselore.org << "EOF"
            mkdir -p /root/courselore/
            rm -rf /root/courselore--deploy/
            mkdir /root/courselore--deploy/
            mv /root/courselore--ubuntu--${{ github.ref_name }}.tar.gz /root/courselore--deploy/courselore--ubuntu--${{ github.ref_name }}.tar.gz
            cd /root/courselore--deploy/
            tar -xzf ./courselore--ubuntu--${{ github.ref_name }}.tar.gz
            systemctl stop courselore || true
            cp /root/courselore--deploy/courselore/_/configuration/courselore.service /etc/systemd/system/courselore.service
            systemctl daemon-reload
            mv /root/courselore/courselore/ /root/courselore--deploy/courselore--old/ || true
            mv /root/courselore--deploy/courselore/ /root/courselore/courselore/
            systemctl start courselore
            rm -rf /root/courselore--deploy/
          EOF
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@main
      - uses: softprops/action-gh-release@master
        with:
          files: ./**/*.*
